image: node:14
stages:
  - deploy
  - e2e

pages:
  stage: deploy
  cache:
    paths:
    - node_modules/
  script:
  - yarn
  - PUBLIC_PATH=https://deepexi.gitlab.io/<%=folder%>/ API_SERVER=https://easy-mock.com/mock/5c1b3895fe5907404e654045/femessage-mock yarn build
  - mv dist public
  artifacts:
    paths:
    - public
  only:
  - master

cypress:
  image:
    name: cypress/included:6.0.1
    entrypoint: [""]
  stage: e2e
  when: manual
  tags:
    - docker
  script:
    - cypress run --env config=dev
  artifacts:
    paths:
      - test/e2e/screenshots
      - test/e2e/video
    expire_in: 3 day